And although this smacks a bit of eccentricity,
It’s really rather clever
For there after you will never
You will NEVER NEVER NEVER
Have the slightest need for using electricity.’
(At which, no less than fifty-two
Policemen cried, ‘If this is true
That creature’ll get some fabulous publicity!’)
‘And here we have Miss Spider
With a mile of thread inside her
Who has personally requested me to say
That she‘s NEVER met Miss Muffet
On her charming little tuffet –
If she had she‘d NOT have frightened her away.
Should her looks sometimes alarm you
Then I don’t think it would harm you
To repeat at least a hundred times a day:
“I must NEVER kill a spider
I must only help and guide her
And invite her in the nursery to play.” ’
(The Police all nodded slightly,
And the Firemen smiled politely,
And about a dozen people cried, ‘Hooray!’)
‘And here’s my darling Ladybird, so beautjul, so kind,
My greatest comfort since this trip began.
She has four hundred children and she’s left them all behind,
But they’re coming on the next peach of the can.’
(The Cops cried, ‘She’s entrancing!’
All the Firemen started dancing,
And the crowds all started cheering to a man!)
‘And now, the Silkworm,’ James went on,
‘Whose silk will bear comparison
With all the greatest silks there are
In Rome and Philadelphia.
If you would search the whole world through
From Paraguay to Timbuctoo
I don’t think you would find one bit
Of silk that could compare with it.
Even the shops in Singapore
Don’t have the stuff. And what is more,
This Silkworm had, I’ll have you know,
The honour, not so long ago,
To spin and weave and sew and press
The Queen of England’s wedding dress.
And she’s already made and sent
A waistcoat for your President.’
(‘Well, good for her!’ the Cops cried out,
And all at once a mighty shout
Went up around the Empire State,
Let’s get them down at once! Why WAIT?’)
Thirty-eight
Five minutes later, they were all safely down, and James was excitedly telling
his story to a group of flabbergasted officials.
And suddenly – everyone who had come over on the peach was a hero! They
were all escorted to the steps of City Hall, where the Mayor of New York made
a speech of welcome. And while he was doing this, one hundred steeplejacks,
armed with ropes and ladders and pulleys, swarmed up to the top of the Empire
State Building and lifted the giant peach off the spike and lowered it to the
ground.
Then the Mayor shouted, ‘We must now have a ticker-tape parade for our
wonderful visitors!’
And so a procession was formed, and in the leading car (which was an
enormous open limousine) sat James and all his friends.
Next came the giant peach itself. Men with cranes and hooks had quickly
hoisted it on to a very large truck and there it now sat, looking just as huge and
proud and brave as ever. There was, of course, a bit of a hole in the bottom of it
where the spike of the Empire State Building had gone in, but who cared about
that – or indeed about the peach juice that was dripping out of it on to the street?
Behind the peach, skidding about all over the place in the peach juice, came
the Mayor’s limousine, and behind the Mayor’s limousine came about twenty
other limousines carrying all the important people of the City.
And the crowds went wild with excitement. They lined the streets and they
leaned out of the windows of the skyscrapers, cheering and yelling and
screaming and clapping and throwing out bits of white paper and ticker-tape, and
James and his friends stood up in their car and waved back at them as they went
by.
Then a rather curious thing happened. The procession was moving slowly
along Fifth Avenue when suddenly a little girl in a red dress ran out from the
crowd and shouted, ‘Oh, James, James! Could I please have just a tiny taste of
your marvellous peach?’
‘Help yourself!’ James shouted back. ‘Eat all you want! It won’t keep for
ever, anyway!’
No sooner had he said this than about fifty other children exploded out of the
crowd and came running on to the street.
‘Can we have some, too?’ they cried.
‘Of course you can!’ James answered. ‘Everyone can have some!’
The children jumped up on to the truck and swarmed like ants all over the
giant peach, eating and eating to their hearts’ content. And as the news of what
was happening spread quickly from street to street, more and more boys and
girls came running from all directions to join the feast. Soon, there was a trail of
children a mile long chasing after the peach as it proceeded slowly up Fifth
Avenue. Really, it was a fantastic sight. To some people it looked as though the
Pied Piper of Hamelin had suddenly descended upon New York. And to James,
who had never dreamed that there could be so many children as this in the world,
it was the most marvellous thing that had ever happened.
By the time the procession was over, the whole gigantic fruit had been
completely eaten up, and only the big brown stone in the middle, licked clean
and shiny by ten thousand eager little tongues, was left standing on the truck.
Thirty-nine
And thus the journey ended. But the travellers lived on. Every one of them
became rich and successful in the new country.
The Centipede was made Vice-President-in-Charge-of-Sales of a high-class
firm of boot and shoe manufacturers.
The Earthworm, with his lovely pink skin, was employed by a company that
made women’s face creams to speak commercials on television.
The Silkworm and Miss Spider, after they had both been taught to make nylon
thread instead of silk, set up a factory together and made ropes for tightrope
walkers.
The Glowworm became the light inside the torch on the Statue of Liberty, and
thus saved a grateful City from having to pay a huge electricity bill every year.
The Old-Green-Grasshopper became a member of the New York Symphony
Orchestra, where his playing was greatly admired.
The Ladybird, who had been haunted all her life by the fear that her house was
on fire and her children all gone, married the Head of the Fire Department and
lived happily ever after.
And as for the enormous peach stone – it was set up permanently in a place of
honour in Central Park and became a famous monument. But it was not only a
famous monument. It was also a famous house. And inside the famous house
there lived a famous person –